# A sample Gemfile
source "https://rubygems.org"

gem "twitter", "5.10.0"
gem "activerecord"
gem "sqlite3"
gem "pg"
gem "rake"
gem "logger"
gem "msgpack"
gem "redis"
gem "hiredis"
gem "redis-objects"
gem "nokogiri"
gem "sanitize"
gem "dotenv"
